# ALL
nhn:
  cloud:
    security:
      url: "https://api-keymanager.nhncloudservice.com/keymanager/v1.0/appkey/{appkey}/secrets/{keyid}"
      password: "baegopa-project"
      appkey: "fxR0BKQWZ6UGUhZQXX6v"

#'dev' profile only
---
spring:
  config:
    activate:
      on-profile: dev

#'prod' profile only
---
spring:
  config:
    activate:
      on-profile: prod